steps:
- uses: actions/checkout@v4
- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.x'
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -e ./
    pip3 install torch torchvision torchaudio
    pip install pytest
- name: Test with pytest
  run: |
    pytest ./